### ISSUE TITLE
Browser-based client issues

### ISSUE THREAD

**Issue by dradtke** [Ezelia/eureca.io#18]
I'm working on an application that uses a customized Go-based server to communicate with a Eureca.io client, and I've noticed some discrepancies between how the client behaves depending on whether it's run via node, or in a browser.

The following client code works fine when run using Node:

```js
var Eureca = require('eureca.io');
var client = new Eureca.Client({
    uri: 'ws://localhost:6400',
    prefix: 'rpc',
    transport: 'websockets',
    autoConnect: true
});
```

but when I try to do the same thing in a browser, something weird starts to happen. It basically ignores the prefix and transport specified, and starts sending polling requests to `http://localhost:6400/eureca.io/`.

I started hacking together some fixes, but I can't help but feel that they're just band-aids over a fundamental piece of communication that's not working correctly. I got it to start using the right prefix by modifying the line...

```js
if (typeof Primus != "undefined") Primus.prototype.pathname = "/eureca.io";
```

...and I got it to (kind of) start using websockets by changing the order of the transports in the "don't avoid websockets" case here:

```js
transports: !primus.AVOID_WEBSOCKETS ? ['polling', 'websocket'] : ['polling']
```

That ends the polling attempts, but it doesn't seem like it's properly initiating the connection either.

These changes were made to the `/eureca.js` file generated by the Node server, which I just saved to a different location.

Any tips?

**Comment by alaa-eddine** [comment]
Hi,
Please note that eureca.io rely on primus to handle connections.
Primus provide an interface to communicate using different frameworks : websockets, engine.io, faye, sockjs ...etc  all of them serve the same purpose (realtime communication) but each of them has a specific implementation.

Some framewoks will start wih http polling then upgrade to the best protocole available (xhr, ws ...etc)
Some frameworks have a different approach, they start trying with the best known protocole then downgrade if not available.

the transport field do not specify a protocole (xhr, ws ...etc) but it specify the used library (engine.io, faye, websocket, sockjs)

if your concern is to provide communication throught websocket protocole, I'd recommand you to use engine.io transport, it's reliable and will allways manage to provide you with the best transport available.
you may see some polling, but if WS is available it'll use it (you can inspect this from Chrome devtools > network > ws) 



About the generate eureca.js file, it's not recommanded to modify it manually because it's generated on the fly by primus, then eureca.io will add some specific information.
if you update eureca.io or change the transport library, the file will be regenerated to include the specific code for the new transport library.

About the pathname '/eureca.io' this have nothing to do with the protocole itself, it's just used to identify eureca.io queries when debugging.
you can configure custom pathname if you want to, but it'll not change the way that a specific framework use to communicate with the server.



is there any reason why you are using websocket framework instead of engine.io or sockjs ?
