### ISSUE TITLE
Messages discarded when using asynchronous returns

### ISSUE THREAD

**Issue by mehcode** [Ezelia/eureca.io#22]
Multiple successive calls to an asynchronously returning method cause all but the final call to be discarded. From the client code below, only the second `console.log` is hit.

---

**Client**

```js
var Eureca = require('eureca.io');
var client = new Eureca.Client({ uri: 'ws://localhost:8000/'});

client.ready(function(proxy) {
  proxy.asyncServerHello().onReady((function(result) {
    console.log(result);
  }));

  proxy.asyncServerHello().onReady((function(result) {
    console.log(result);
  }));
});
```

**Server**

```js
var http = require('http');
var httpServer = http.createServer();
var Eureca = require('eureca.io');
var eurecaServer = new Eureca.Server();
eurecaServer.attach(httpServer);

eurecaServer.exports.asyncServerHello = function() {
  var context = this;
  context.async = true;

  setTimeout(function() {
    context.return("Async hello from server!")
  }, 2000);
}

httpServer.listen(8000);
```

**Comment by alaa-eddine** [comment]
Good catch,

I did some debug and found that all calls arrives to the server and are executed, but only the first async call result is returned.

I'll dig into this and push a patch asap.

**Comment by alaa-eddine** [comment]
Hi,
I pushed a fix for this issue right now :) 
Please note that it's still not available on npm because I need to do further tests before updating the production package, but you can use the dev version from this repo.
 
the easiest way if you have already installed eureca.io using npm is to replace node_modules/eureca.io/lib/*.js with the two js files here : https://github.com/Ezelia/eureca.io/tree/master/lib

**Comment by mehcode** [comment]
Seems that's it's fixed. Thank you sir.
