### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by Dreaded-Gnu** [Ezelia/eureca.io#24]
Hello,
I want to use your library for a multiplayer typescript game.

Is there a typescript definition file existing for eureca.io, or can it be generated automatically when building the project via grunt manually?

**Comment by alaa-eddine** [comment]
Hi, 
Yes you can generate the .d.ts definitions files by setting "declaration" argument to true in the gruntfile.

I just don't use them because there are some dynamically generated code and some generic types that get tricky when using typescript definitions.

I highly recommand you to rely more on the documentation (http://eureca.io/doc/) and examples  (https://github.com/Ezelia/eureca.io/tree/master/examples)
