### ISSUE TITLE
Strange issue when calling client methods from server

### ISSUE THREAD

**Issue by DenianArthurShades** [Ezelia/eureca.io#32]
Hi,

I've got a strange kind of problem here, and I don't really know how to debug this.

The situation is like this: My node application is part server, part proxy - it serves some files on its own, but for some things, it has to make a call to another server. Now, since http(s) calls from node are asynchronous, I had to do some crazy twice-asynchronous stuff.

The eureca client exports a resolve and a reject function, the server exports several functions. Basically, in most cases, this happens:
1. Client calls server function
2. Server calls to http, saves the promise (let's call it httpPromise)
3. Server returns randomly generated function call id
4. Client saves a promise (functionPromise), identified by the function call id
5. httpPromise gets resolved, calls either client.resolve or client.reject with function call id and the result
6. Client resolves/rejects functionPromise

Most of the time, this works. for one of the exposed server methods, though, this only works the first time after the node script starts - after that, my script still gets to the client.resolve call (I checked that), but the call is never sent over the websocket. All other server methods still work, even with repeated calls.

Do you have any idea what could be responsible for this, or how I could debug this case further?

**Comment by alaa-eddine** [comment]
Hi,

Seems like you are re-implementing a part of eureca.io :)
I think that for your asynchronous stuff you can use the builtin asynchronous feature : see example here https://github.com/Ezelia/eureca.io/tree/master/examples/5-async-returns
(note that he .onReady() can be replaced with .then() which is the standard syntax for promises, I just didn't updated the examples yet).

as for you issue, if you still want to implement it yourself, it'll be very hard to guess what's going wrong without debugging and without seeing the code :) 
if your client is web based, you need to enable chrome dev tools, Networking tab and see what's exchanged here (within the websocket)

in the server side, set the environment variable Debug=* then run your server, you'll see detailled logs of what's going on.

the way you describe the error let met think that you have an issue with the generated functionID 
maybe you are using the same id for some reason, this usually happens when you generate some ides inside an async function executed inside a loop.


I highly recommand you to take a look at eureca.io async feature, I think that it can save you some precious time ;)

**Comment by DenianArthurShades** [comment]
Ok, good to know that asynchronous returns are already possible... should have looked at the examples. Basically the only advantage of my implementation is that I use the full promise syntax, so I can actually reject a promise from the server to the client. I would have implemented notify, but I never used that.

The problem remains that, for some reason, calling clientProxy.resolve on the server with the exact same parameters works the first time, but sends nothing over the websocket the second time...

**Comment by alaa-eddine** [comment]
you can reject with eureca.io too ;)

the syntax is   .then(successfunction, failure function) .
it'll still need some custome code to maintain your consistency, but it's totally possible.

it's not simple to help you find what's wrong without seeing the code ;)
