### ISSUE TITLE
Use Promises?

### ISSUE THREAD

**Issue by pkese** [Ezelia/eureca.io#33]
I don't quite understand the reasoning behind choosing the `onReady`, `this.context` and `context.async` instead of handling async stuff with the standard Promise objects.

Most libraries nowadays would simply check if the return value of a rpc function call is an immediate value (so return it immediately) or if it is a Promise object (`typeof result['then'] === 'function'`) and then wait on `then()` to return result (optionally also pass the result of `catch` forward it to client)?

Similar on client side, one should be able to write `serverProxy.add(1,2).then(result=>{...}).catch(error=>{...})`

Is there a reason for not adhering to standards?

**Comment by alaa-eddine** [comment]
Hi @pkese , the only reason here is backward compatibility since I'm not sure if some old nodejs version support promises correctly.
eureca.io was developed before promises bacome standard, so I found this solution to provide asynchronous returns.
I also need the context.async for internal verification, not sure if I can achieve the remote execution correctly without it.

btw, the onReady syntax is deprecated, you should use .then(success, error) instead, but context.async=true is still needed for now. this is an effort to standardise the syntax before switching to true promises.

**Comment by alaa-eddine** [comment]
one precision : setting context.async to true, is only important when the user want to implement his custom async code. I need this because I don't know hos the user implements his async routine.

your example serverProxy.add(1,2).then(result=>{...}) shoud work just fine but without the .catch()

**Comment by pkese** [comment]
@alaa-eddine thanks for your answer. It makes sense, so I'll close the issue.
