### ISSUE TITLE
WebRTC not working?

### ISSUE THREAD

**Issue by Lallassu** [Ezelia/eureca.io#36]
Is the WebRTC mode broken? Tried it in my app and it doesn't connect to the server. Also tried the sample 7-WebRTC app in examples and same issue there.

No errors or anything, it just doesn't connect to the backend.

**Comment by alaa-eddine** [comment]
Hi @Lallassu 
WebRTC mode is experimental because there is no official nodejs WebRTC support.

to get WebRTC working, you need to install this [implementation of a node WebRTC stack](https://github.com/js-platform/node-webrtc).  then run the eureca server code from the machine where node-webrtc is installed.

please note that the above solution only work on linux and OSX .

hopefully, nodejs will add native WebRTC in a future version, so I can focus on a more stable solution.

**Comment by Lallassu** [comment]
Oh, I see, Thanks for the information!
